name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'V$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels: ['feature']
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '* No changes'

template: |
  ## What's Changed
  $CHANGES
