name: module3_task2

on:
  push:
    branches: [main. master]
  pull_request:

jobs:
  continuous-delivery:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run linting
        run: make lint

      - name: Build package
        run: make package

      - name: Archive package (only on main/master)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: awesome-website-package
          path: awesome-website.zip