name: module3_task0

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 8 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Execute make help.
        run: |
          cd $GITHUB_WORKSPACE/module3_task0/
          make build
